name: make_jisyo

#on:
#  schedule:
#    - cron: "0 21 * * *"
#  workflow_dispatch:

#on: [push, pull_request, workflow_dispatch]
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  make_jisyo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Python をセットアップ
        uses: actions/setup-python@v6

      - name: Python ライブラリをセットアップ
        run: |
          sudo apt update
          sudo apt install -y python3-lxml
          sudo apt install -y python3-regex

      - name: コマンドをセットアップ
        run: |
          sudo apt update
          sudo apt install -y wget curl

      - name: make test
        run: |
          echo "cron追加したよ"
          ls -a
          which bash
          make test
          ls -a

      - name: Upload binaries to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "mozc.txt,skk.txt"
          bodyFile: "body.md"
