name: make_jisyo

#on:
#  schedule:
#    - cron: "0 21 * * *"
#  workflow_dispatch:

on: [push, pull_request, workflow_dispatch]

jobs:
  make_jisyo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - run: echo "cron追加したよ"
      - run: ls -a
      - run: ./build.sh

