name: make_jisyo_cron

on:
  schedule:
    - cron: "0 0 10 * *" # 分、時、日、月、曜日？毎月15日の 00:00 UTC（日本時間 09:00）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  make_jisyo_cron:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Git 設定
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: タグ作成
        id: tag
        run: |
          TAG="v$(date +'%Y.%m.%d')"
          # すでにタグが存在する場合は時分秒を付与
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            TAG="v$(date +'%Y.%m.%d-%H%M%S')"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git tag $TAG
          git push origin $TAG

      - name: Python をセットアップ
        uses: actions/setup-python@v6

      - name: Python ライブラリをセットアップ
        run: |
          sudo apt update
          sudo apt install -y python3-lxml
          sudo apt install -y python3-regex

      - name: コマンドをセットアップ
        run: |
          sudo apt update
          sudo apt install -y wget curl mailutils

      - name: make honban
        run: |
          make honban

      - name: Upload binaries to release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.tag }}
          artifacts: "output/mozc_all.txt,output/mozc_over3.txt,output/skk_all.txt,output/skk_over3.txt,output/msime_all.txt,output/msime_over3.txt"
          bodyFile: "body.md"

      - name: send mail
        run: |
          echo ${{ secrets.EMAIL }}
          echo test | mail -s "test" ${{ secrets.EMAIL }}
